### ISSUE TITLE
SharpHook Issue

### ISSUE THREAD

**Issue by MudkipWorld** [Darnoman/Godot-GlobalInput-Addon#5]
I really love the addon, it has helped me so much with making my Desktop Pet widget, but the addon seems windows exclusive only, which is fine, by all means. 

A quick question came to mind, wouldn't using a library like [https://github.com/TolikPylypchuk/SharpHook](url) help make it easier to make the addon cross platform and help add the listed missing features?

I sadly don't have much C# experience, but I still felt like mentioning the library could help you at some point if you were wanted to make the addon not strictly for windows only!

**Comment by Darnoman** [comment]
I do have a branch for sharphook.. if you want to take a look. Lmk if you can see it. I don't have a Linux or a Mac/IOS so im unable to test sharphook to see if it works on those platforms. It should work on windows though. If you'd like to test it out and let me know if you run into issue that'd be a great help.

**Comment by MudkipWorld** [comment]
Ah, I see it now, didn't notice it earlier. Sorry for the confusion ^^;
Thanks for letting me know btw!

**Comment by MudkipWorld** [comment]
Hey, sorry for reopening the issue, but I am having a bit of a problem with the SharpHook addon ^^;
In my app, you can have "States" that you can rebind keys to. However, this seems to not work with the addon for some reason.

![issue](https://github.com/user-attachments/assets/b8bbd44c-22c3-4294-b009-20993755a02d)
 
 rebinding code : 
![IssueScreenshot1](https://github.com/user-attachments/assets/0421ad02-894a-409a-a17d-19646764769b)

 the part where it detects the input :
 
![IssueScreenshot2](https://github.com/user-attachments/assets/adbc6052-d849-4c73-a27e-eead2218af77)

**Comment by Darnoman** [comment]
so from what im seeing on my side of trying to reproduce this issue is that when new action/inputs are added, they aren't being added to the "ActionDictionary" within the globalinput. I'll let you know once i've fixed this issue

**Comment by Darnoman** [comment]
Okay I know what the issue is. So when I created this pluggin, I assumed that the inputs were gunna be static. And so what's happening is that when you put in a new keybind, it doesn't update the GlobalInput's internal InputMap called ActionDictionary. This is what's causing the null returns. I've solved it on my end, through some janky code just need to think of a way to make it neater.

**Comment by Darnoman** [comment]
(GlobalInputCSharp.cs line 375)
![image](https://github.com/user-attachments/assets/1a798a8e-442f-45e2-9b4a-3934194bc932)

(GlobalInputCSharp.cs line ~400-405)
![image](https://github.com/user-attachments/assets/7cc37b08-da1a-4ad9-9104-6e2f1afd3727)

those should fix ur issues for now... until i find a more permanent solution


https://github.com/user-attachments/assets/e7df82de-21aa-40dd-ab34-0397b7e2972d

**Comment by MudkipWorld** [comment]
Thanks for your answer, I guess the issue should still be open since it isn't 100% fixed?

**Comment by Darnoman** [comment]
alright I pushed an update. Let me know if you run into other issues. (also do you think I should just make sharphook the main branch?)

**Comment by MudkipWorld** [comment]
Thanks for the quick fix, for the main branch thing, it is up to you. I say if you feel like it could give wider support and ease of use, go for it!
